
# ============================================================
#  Auto-generated by CmDaB for package: upnp
# ============================================================

# ---- avoid recursion into our own configs ----
set(_cmdab_saved_prefix "${CMAKE_PREFIX_PATH}")
list(REMOVE_ITEM CMAKE_PREFIX_PATH ".../configs")

# ---- try real config first ----
find_package(upnp CONFIG QUIET)

# ---- restore prefix path ----
set(CMAKE_PREFIX_PATH "${_cmdab_saved_prefix}")

# ---- delegate everything to CmDaB ----
CmDaB_Resolve(upnp)
